name: Build And Release MacOS X App

on:
  push:
    tags:
      - "v*"

jobs:
  build_and_release:
    name: "Build And Release - Python ${{ matrix.python-version }}"
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install py2app

      - name: Build macOS App Bundle
        run: python setup.py py2app

      - name: Compress (Tar) The App Bundle
        run: tar -czf dist/metview-python-${{ matrix.python-version }}.app.tar.gz -C dist metview.app

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/metview-python-${{ matrix.python-version }}.app.tar.gz
