name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "OS: ${{ matrix.os }} - Python: ${{ matrix.python-version }}"

    runs-on: ${{ matrix.os }}

    env:
      QT_QPA_PLATFORM: offscreen  # Prevents GUI-related errors in headless environments

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # IMPORTANT: Fixes a `Warning: Qt.py [warning]: ImportError(QtGui): libEGL.so.1: ...` error
      - name: Install Dependencies (Ubuntu only)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install -y \
            libxcb-cursor0 libxkbcommon-x11-0 libxcb-keysyms1 \
            libxcb-xinerama0 libxcb-xfixes0 libxcb-shape0 libxcb-randr0 \
            libxcb-render-util0 libxcb-shm0 libxcb-icccm4 libxcb-image0 \
            libegl1 libopengl0

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox and any other packages
        run: python -m pip install tox

      - name: Bootstrap
        run: python -m pip install -e .

      - name: Test
        run: tox -e python-${{ matrix.python-version }}
